---
 - name: "java installed or not
   command: "java -version"
   register: prereq_java
   changed_when: false
 - name: Installation of java only when it is not installed
   yum: 
      name: openjdk
